--- #YAML:1.0
name:               Running-Commentary
version:            0.000005
abstract:           call C<system> cleanly, with tracking messages
author:
    - Damian Conway <DCONWAY@CPAN.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:      0
    Keyword::Simple:   0
    Lexical::Failure:  0
    List::Util:        0
    perl:              5.014
    Scalar::Util:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
